### ISSUE TITLE
Enhancement: Expanding the wiki to include setup regarding issue #12

### ISSUE THREAD

**Issue by CC007** [Alan-Gomes/mcspring-boot#14]
A couple of configuration and setup things were expanded on in issue #12 to properly be able to use spring boot starter dependencies including

 - maven shading setup
 - classloader setup

These should be mentioned in the getting started guide.

**Comment by Alan-Gomes** [comment]
I added the documentation in [known issues](https://github.com/Alan-Gomes/mcspring-boot/wiki/Known-issues) and [getting started](https://github.com/Alan-Gomes/mcspring-boot/wiki/Getting-started) sections. Thanks!
