### ISSUE TITLE
Error No qualifying bean of type 'dev.alangomes.springspigot.context.Context'

### ISSUE THREAD

**Issue by lucasfrederico** [Alan-Gomes/mcspring-boot#16]
Ao tentar iniciar o meu servidor, após implementar em meu plug-in o comando de "heal", conforme no exemplo da documentação, eu recebo o erro abaixo.

![image](https://user-images.githubusercontent.com/55282018/67161069-5106f880-f32d-11e9-9fcc-fc7f53371092.png)

**Comment by Alan-Gomes** [comment]
Tente usar essa configuração no seu pom.xml:

https://github.com/Alan-Gomes/mcspring-boot/issues/12#issuecomment-497897220

**Comment by lucasfrederico** [comment]
Funcionou! Obrigado.
