### ISSUE TITLE
application.properties is not being picked up

### ISSUE THREAD

**Issue by jordieh** [Alan-Gomes/mcspring-boot#5]
Hello,

My directory structure looks like this:
![Directory structure](https://i.postimg.cc/yN9V84tC/afbeelding.png)
The problem is that Spring doesn't pick up the `application.properties` file.

I'am initializing the application like this:
```java
/* ... */ onEnable() {
ResourceLoader rl = new DefaultResourceLoader(getClassLoader());
applicationContext = new SpringApplicationBuilder(ApplicationClass.class)
       .resourceLoader(rl)
       .initializers(new SpringSpigotInitializer(this))
       .run();
}
```
I have the following entry in my Maven build section:
```xml
    <resources>
        <resource>
            <directory>src/main/resources</directory>
            <filtering>true</filtering>
            <includes>
                <include>plugin.yml</include>
                <include>application.properties</include>
                <include>banner.txt</include>
            </includes>
        </resource>
    </resources>
```
My `application.properties` file looks like this:
```properties
spring.application.title=testApplication
spring.main.banner-mode=off
```
And my `banner.txt` contains this line: `TEST: ${application.title}`

The output is `TEST:` which means the `application.properties` file isn't being recognized.

Thanks in advance.

**Comment by Alan-Gomes** [comment]
Hello, after analyzing the behavior of spring, I noticed that it does not work well with class loader of the plugin, as a workaround, you can load the properties file before the application startup:

```java
Properties props = new Properties();
props.load(getClassLoader().getResourceAsStream("application.properties"));

applicationContext = new SpringApplicationBuilder(ApplicationClass.class)
       .resourceLoader(rl)
       .properties(props)
       .initializers(new SpringSpigotInitializer(this))
       .run();
```

**Comment by jordieh** [comment]
That seems to have fixed the problem. I don't know if this is related to it though, but the log formatting also doesn't seem to be working:
```properties
logging.level.root=WARN
logging.pattern.console=%5p # {%15.15t, %-40.40logger}: %m
```
Just spits out everything the loggers have to offer (even debug level messages)

**Comment by Alan-Gomes** [comment]
Unfortunately, the log is managed by the server, so it is necessary to change the internal settings. This tutorial may help you:

https://www.spigotmc.org/threads/tut-how-to-configure-remove-the-layout-of-logging-in-the-spigot-console.155727/

**Comment by CC007** [comment]
I found that you can set the logging properties using a logback.xml file, since logback is the default logger of spring:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>

    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d{yyyy-MM-dd HH:mm:ss} | %-5p | [%thread] %logger{5}:%L - %msg%n</pattern>
        </encoder>
    </appender>

    <appender name="FILE" class="ch.qos.logback.core.FileAppender">
        <file>logFile.log</file>
        <append>true</append>
        <encoder>
            <pattern>%d{yyyy-MM-dd HH:mm:ss} | %-5p | [%thread] %logger{5}:%L - %msg%n</pattern>
        </encoder>
    </appender>

    <root level="DEBUG">
        <appender-ref ref="STDOUT" />
        <appender-ref ref="FILE" />
    </root>

</configuration>
```

You might want to change this in your wiki.
