### ISSUE TITLE
CommandLine::getUsageMessage returns message with carrage returns

### ISSUE THREAD

**Issue by CC007** [Alan-Gomes/mcspring-boot#8]
When trying to send the usage message to the player, by writing: 
```java
CommandLine cmd = commandSpec.commandLine();
if (cmd.isUsageHelpRequested()) {
	context.getPlayer().sendMessage(cmd.getUsageMessage());
}
```
The resulting message contains carrage returns (`\r`) that are displayed in minecraft as a square with letters inside in minecraft. It would be nice if `getUserMessage` were to create the message without the carrage returns, so that they dont have to be filtered out manually before sending the message to the player.

(I am using Windows 10 with Minecraft java edition 1.13.2 on the client side and spigot 1.13.2 with mcspring-boot 0.10.0 on the server side)

**Comment by Alan-Gomes** [comment]
Have you tried `cmd.getUsageMessage(Ansi.OFF)`? It disallows some customizations in the output, should work for your case

**Comment by CC007** [comment]
Thanks, I'll try that.

**Comment by Alan-Gomes** [comment]
Keep me updated ;)

**Comment by CC007** [comment]
![image](https://user-images.githubusercontent.com/5381337/58041712-10664180-7b39-11e9-80c8-6515d81b7fc2.png)

This is with Ansi.OFF added.

**Comment by Alan-Gomes** [comment]
Can you provide me a more complete code? I want to know the source of your `commandSpec`

**Comment by CC007** [comment]
It is those same code samples as from https://github.com/Alan-Gomes/mcspring-boot/issues/7#issuecomment-494018111

**Comment by Alan-Gomes** [comment]
This problem has been fixed [here](https://github.com/Alan-Gomes/mcspring-boot/commit/da0b49e9379cd77d6d2969ec03f44ea548194dd6#diff-6b3ee54fdf3a52a45ea7c23fa0eb72b2R67) and it will arrive as soon as possible on 0.11.1

Thanks :)
