### ISSUE TITLE
Creating a bean of the plugin class causes issues

### ISSUE THREAD

**Issue by CC007** [Alan-Gomes/mcspring-boot#9]
If someone creates a bean of their class that extends JavaPlugin, it causes an issue where it can't resolve a Plugin bean somewhere in your code, because there are now 2 Plugin beans available in the spring context. 

The reason to create your own bean is to provide the ability to call plugin specific methods inside the user created JavaPlugin child class. Whether or not it is bad design to add extra methods in that class is up for debate, but I don't think it should be something to be enforced by a design limitation of your plugin.

What you could do is add a qualifier to the uses of the bean (or rename the autowired variable to match the bean name), to prevent conflicts.

**Comment by Alan-Gomes** [comment]
If I understand it correctly, you are trying to autowire the plugin instance inside another bean, it should be possible, just make sure to **do not** annotate the JavaPlugin class with `@Component`.

Example:
```java
public class TestPlugin extends JavaPlugin {

    private ConfigurableApplicationContext context;

    @Override
    public void onEnable() {
        // init code
    }

    @Override
    public void onDisable() {
        context.close();
        context = null;
    }

}
```	

```java
@Component
public class AnotherBean {

    @Autowired
    private TestPlugin testPlugin;

}
```

**Comment by Alan-Gomes** [comment]
Let me know if this answer solves your problem, if so, I can close this issue :)

**Comment by Alan-Gomes** [comment]
I am closing this issue due to the lack of response. You can reopen it if my answer has not solved your problem :)
